// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jchdcphtlhgefybhioir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjaGRjcGh0bGhnZWZ5Ymhpb2lyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDk3NDEsImV4cCI6MjA2NjU4NTc0MX0.uZItONWmMeRd7s-i0aMG9IVEEDLGS73zz2uhGOjcy78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);